data_path:
  - 'penguins.csv'


general:
  random_state: 42
  test_size: 0.2
  cv_folds: 5


model_1_name: 'k_means'
k_means_params:
  n_clusters: [2, 3, 4, 5]
  init: ['k-means++', 'random']


model_2_name: 'gaussian_mixture'
gaussian_mixture_params:
  n_components: [2, 3, 4, 5]
  covariance_type: ['full', 'tied']


model_3_name: 'dbscan'
dbscan_params:
  eps: [0.3, 0.5, 0.7]
  min_samples: [3, 5, 7]
