data_path:
  - 'penguins.csv'


general:
  random_state: 42
  test_size: 0.2
  cv_folds: 5


Model 1 Name: 'KMeans'
kmeans_params:
  n_clusters: [2, 3, 4, 5]
  init: ['k-means++', 'random']


Model 2 Name: 'GaussianMixture'
gaussianmixture_params:
  n_components: [2, 3, 4, 5]
  covariance_type: ['full', 'tied']


Model 3 Name: 'DBSCAN'
dbscan_params:
  eps: [0.3, 0.5, 0.7]
  min_samples: [3, 5, 7]
